import * as THREE from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {createPhone} from './phone.js';
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const scene=new THREE.Scene();scene.background=new THREE.Color('#c6deeb');scene.fog=new THREE.Fog('#c6deeb',100,240);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,500);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;$('#viewport').append(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe8f4ff,0x7a8168,2.4));const sun=new THREE.DirectionalLight(0xfff6df,2.5);sun.position.set(-30,80,35);scene.add(sun);
let model,route,points,segments,total,travel=0,yaw=-Math.PI/2,pitch=-.06,view='walk',playing=false,hold=0,ready=false,referenceSphere,referenceToken=0;
let phone=null;
const routeGroup=new THREE.Group();scene.add(routeGroup);const textureLoader=new THREE.TextureLoader();const textures=new Map();
function positionAt(distance){const seg=distance<=segments[0]?0:1;const local=seg?distance-segments[0]:distance;return points[seg].clone().lerp(points[seg+1],clamp(local/segments[seg],0,1));}
function nearest(){return [0,segments[0],total].map((d,i)=>({d:Math.abs(d-travel),i})).sort((a,b)=>a.d-b.d)[0].i;}
function stopName(){if(travel<.05)return 'P01';if(Math.abs(travel-segments[0])<.05)return 'P02';if(total-travel<.05)return 'P03';return travel<segments[0]?'P01 → P02':'P02 → P03';}
function updateUI(){if(!ready)return;$('#progress').value=Math.round(travel/total*1000);$('#distance').textContent=`${travel.toLocaleString('pt-PT',{maximumFractionDigits:1,minimumFractionDigits:1})} / ${total.toLocaleString('pt-PT',{maximumFractionDigits:1})} m`;$('#position').textContent=view==='reference'?`Referência · P0${nearest()+1}`:stopName();$('#play').textContent=playing?'Ⅱ Pausar':'▶ Percorrer';$('#play').setAttribute('aria-pressed',String(playing));}
function setTravel(value){if(!ready)return;travel=clamp(value,0,total);if(view==='reference')setView('walk');updateUI();}
async function showReference(){const token=++referenceToken;const i=nearest();travel=[0,segments[0],total][i];updateUI();$('#loading').hidden=false;$('#loading').textContent='A carregar o render de referência…';try{let tex=textures.get(i);if(!tex){tex=await textureLoader.loadAsync(route.stops[i].image);tex.colorSpace=THREE.SRGBColorSpace;textures.set(i,tex);}if(token!==referenceToken||view!=='reference')return;if(!referenceSphere){const geometry=new THREE.SphereGeometry(120,64,32);geometry.scale(-1,1,1);referenceSphere=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({depthWrite:false,toneMapped:false}));scene.add(referenceSphere);}referenceSphere.material.map=tex;referenceSphere.material.needsUpdate=true;referenceSphere.position.copy(points[i]);referenceSphere.rotation.y=route.stops[i].reference_rotation_rad??0;referenceSphere.visible=true;}catch(e){$('#notice').textContent='Não foi possível carregar o render D5.';setView('walk');console.error(e);}finally{if(token===referenceToken)$('#loading').hidden=true;}}
function setView(mode){if(!ready)return;if(mode!=='reference')$('#loading').hidden=true;view=mode;playing=false;hold=0;referenceToken++;if(referenceSphere)referenceSphere.visible=false;model.visible=mode!=='reference';routeGroup.visible=mode==='plan';scene.fog=mode==='reference'?null:new THREE.Fog('#c6deeb',100,240);for(const id of ['walk','plan','reference'])$('#'+id).setAttribute('aria-pressed',String(mode===id));$('#mode').textContent=mode==='reference'?'Render D5 · ponto fixo':mode==='plan'?'Planta 3D · percurso P01–P03':'Modelo base · materiais SketchUp';$('#hint').textContent=mode==='plan'?'Usa a barra para localizar a posição':'Arrasta para olhar à volta';if(mode==='reference')showReference();updateUI();}
$('#help').onclick=()=>{const panel=$('#help-panel');panel.hidden=!panel.hidden;$('#help').setAttribute('aria-expanded',String(!panel.hidden));};
for(const id of ['walk','plan','reference'])$('#'+id).onclick=()=>setView(id);
$('#progress').addEventListener('input',e=>{playing=false;setTravel(Number(e.target.value)/1000*total);});
document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>{playing=false;const mode=view;setTravel([0,segments[0],total][Number(b.dataset.stop)]);if(mode==='reference')setView('reference');});
$('#play').onclick=()=>{if(view==='reference')setView('walk');if(travel>=total-.01)travel=0;playing=!playing;updateUI();};
$('#reset').onclick=()=>{playing=false;setTravel(0);yaw=-Math.PI/2;pitch=-.06;};
for(const [id,direction]of [['back',-1],['forward',1]]){const b=$('#'+id);b.addEventListener('pointerdown',e=>{if(!ready)return;e.preventDefault();b.setPointerCapture(e.pointerId);if(view==='reference')setView('walk');playing=false;hold=direction;});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>hold=0);}
const keys=new Set();addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select,[contenteditable]')||view==='reference'||!ready)return;if(['w','s','a','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){keys.add(e.key);e.preventDefault();}});addEventListener('keyup',e=>keys.delete(e.key));addEventListener('blur',()=>{keys.clear();hold=0;playing=false;updateUI();});
let drag=null;const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY};});canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id||view==='plan')return;yaw-=(e.clientX-drag.x)*.004;pitch=clamp(pitch-(e.clientY-drag.y)*.003,-1.4,1.4);drag.x=e.clientX;drag.y=e.clientY;});for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>drag=null);
const target=new THREE.Vector3();let last=performance.now(),frameStats={count:0,start:last,fps:0};
function frame(now){const dt=Math.min((now-last)/1000,.06);last=now;if(ready){if(view!=='reference'){const gpsTarget=phone?.target();if(gpsTarget!==null&&gpsTarget!==undefined){const delta=gpsTarget-travel;setTravel(travel+Math.sign(delta)*Math.min(Math.abs(delta),dt*1.5));}const moving=(phone?.active()?0:1)*(hold+(keys.has('w')||keys.has('ArrowUp')?1:0)-(keys.has('s')||keys.has('ArrowDown')?1:0)+(playing?1:0));if(moving){setTravel(travel+moving*dt);if(travel>=total||travel<=0){playing=false;updateUI();}}yaw+=(keys.has('a')||keys.has('ArrowLeft')?dt:0)-(keys.has('d')||keys.has('ArrowRight')?dt:0);}
 const pos=positionAt(travel);if(view==='plan'){const mid=points[0].clone().lerp(points[2],.5);camera.position.copy(mid).add(new THREE.Vector3(0,43,.01));camera.up.set(0,0,-1);camera.lookAt(mid);marker.position.copy(pos).setY(pos.y+.8);}else{camera.up.set(0,1,0);camera.position.copy(pos);target.set(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)).add(pos);camera.lookAt(target);const sensorLook=phone?.quaternion();if(sensorLook)camera.quaternion.copy(sensorLook);}
 renderer.render(scene,camera);frameStats.count++;if(now-frameStats.start>1000){frameStats.fps=frameStats.count*1000/(now-frameStats.start);frameStats.count=0;frameStats.start=now;}}
 requestAnimationFrame(frame);}
const marker=new THREE.Mesh(new THREE.SphereGeometry(.4,16,12),new THREE.MeshBasicMaterial({color:0x2077f0}));routeGroup.add(marker);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
new ResizeObserver(entries=>{document.documentElement.style.setProperty('--controls-height',`${entries[0].target.offsetHeight}px`);}).observe($('.controls'));
requestAnimationFrame(frame);
try{route=await(await fetch('./route.json')).json();points=route.stops.map(s=>new THREE.Vector3(...s.position));segments=[points[0].distanceTo(points[1]),points[1].distanceTo(points[2])];total=segments[0]+segments[1];document.documentElement.style.setProperty('--p02',`${segments[0]/total*100}%`);const gltf=await new GLTFLoader().loadAsync('./model.glb');model=gltf.scene;scene.add(model);
 const groundLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points.map(p=>p.clone().setY(p.y+.5))),new THREE.LineBasicMaterial({color:0x2ba977}));routeGroup.add(groundLine);for(const p of points){const m=new THREE.Mesh(new THREE.SphereGeometry(.3,16,12),new THREE.MeshBasicMaterial({color:0xe1a949}));m.position.copy(p);routeGroup.add(m);}routeGroup.visible=false;ready=true;phone=createPhone({getState:()=>({ready,total,gps:route.gps,cumulative:[0,segments[0],total]}),setTravel,setView,lookQuaternion:()=>camera.quaternion.clone()});$('#gps-toggle').disabled=false;$('#motion-toggle').disabled=false;$('#loading').hidden=true;for(const id of ['progress','back','play','forward'])$('#'+id).disabled=false;updateUI();
 // Read-only inspection endpoint for local browser verification.
 window.prototypeDebug={state:()=>({ready,view,travel,total,position:camera.position.toArray(),fps:frameStats.fps,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls,quaternion:camera.quaternion.toArray(),tracking:phone?.phase(),motion:phone?.motionEnabled()}),setTravel,setView,setLook:(y,p)=>{yaw=y;pitch=p;},groundAt:(x,z)=>{const r=new THREE.Raycaster(new THREE.Vector3(x,30,z),new THREE.Vector3(0,-1,0));return r.intersectObject(model,true).slice(0,8).map(h=>({point:h.point.toArray(),material:h.object.material?.name}));},renderer,scene,camera};
}catch(e){console.error(e);$('#loading').textContent='O espaço 3D não carregou. Reabre o protótipo pelo servidor local.';$('#notice').textContent=e.message;}
