(function(root){
const C=typeof module==='object'&&module.exports?require('./movement-core.js'):root.CemMovement,G=typeof module==='object'&&module.exports?require('./geo.js'):root.TourGeo,T=typeof module==='object'&&module.exports?require('./tracking-core.js'):root.VirtualTrackingCore;
function compare(session){if(session.schema!=='cem-movement-1'||!Array.isArray(session.events)||session.events.length>24000)throw Error('Formato de sessão inválido.');const m=session.meta,events=session.events.filter(e=>!['detection','presentation','permissions','fix','axis','mark'].includes(e.type));
 // Motion entries produce activity/step inputs. Derived detections are diagnostic only.
 const results={};for(const mode of ['activity','steps','anchored']){const timeline=C.replay(events.filter(e=>mode!=='anchored'||e.type!=='gps'),{...m,mode});const last=timeline.at(-1);results[mode]={final:last,maxMeters:Math.max(0,...timeline.map(e=>e.alongMeters)),maxOperationalUncertainty:Math.max(0,...timeline.map(e=>e.uncertaintyMeters)),suspendedSamples:timeline.filter(e=>e.status==='suspended').length,samples:timeline.length};}
 // Exact legacy filter with raw fixes and the session's explicitly confirmed origin.
 let origin=null,latest=null,filter=T.createFilter(0,m.total),accepted=0,fixes=0;for(const e of session.events){if(e.type==='fix')latest=e;if(e.type==='anchor'){origin=latest;filter=T.createFilter(0,m.total);accepted=0;}if(e.type==='fix'&&origin){const along=m.location==='site'?T.mapAlong(e,m.geoNodes,m.virtualCumulative).along:G.distance(origin,e);if(e.accuracy<=20&&e.age>=0&&e.age<=10000&&along<=m.total+Math.max(20,e.accuracy)){accepted=filter.add(Math.min(m.total,Math.max(0,along)),e.accuracy,e.stamp,e.stamp+e.age).accepted;fixes++;}}}
 results.baseline={alongMeters:accepted,fixes,geometry:m.location==='site'?'legacy-Benfica':'legacy-radial',note:'Filtro legado sobre fixes brutos; preparação substituída pela âncora explícita da sessão. Não reproduz os 10 s iniciais nem animação 3D.'};return {schema:session.schema,truncated:session.truncated,results,note:'Replay determinístico; sem verdade física automática. Comparar marcações/distâncias medidas. anchored é contrafactual e exige confirmação de início/sentido.'};}
const api={compare};if(typeof module==='object'&&module.exports)module.exports=api;else root.CemReplay=api;
})(typeof window==='undefined'?globalThis:window);
