import * as THREE from 'three';
const $=s=>document.querySelector(s);
export function createPhone({getState,setTravel,setView,lookQuaternion}){
 let active=false,phase='idle',watch=null,token=0,origin=null,preparation=null,filter=null,timer=null,target=null,lastFix=0,lastStamp=-Infinity,lastAccuracy=null;
 let motion=false,motionToken=0,orientation=null,alignment=null,needsAnchor=true,motionAt=0;
 const setStatus=(text)=>{$('#tracking-status').textContent=text;};
 function lock(value){for(const e of document.querySelectorAll('#progress,#back,#forward,#play,#reset,#manual-mode,[data-stop],#tracking-mode'))e.disabled=value;$('#reference').disabled=value;}
 function stop(message='Caminhada parada. Podes iniciar um novo teste.'){token++;active=false;phase='idle';target=null;origin=null;if(watch!==null)navigator.geolocation?.clearWatch(watch);watch=null;clearInterval(timer);timer=null;$('#gps-toggle').textContent='Iniciar caminhada';$('#gps-toggle').setAttribute('aria-pressed','false');$('#use-fix').hidden=true;lock(false);setStatus(message);}
 function activate(position,accuracy){if($('#tracking-mode').value==='site'&&TourGeo.routePosition(position,getState().gps).meters>Math.max(30,accuracy*2)){setStatus('A posição está longe do percurso em Benfica. Escolhe «Teste onde estou».');return;}origin=position;lastAccuracy=accuracy;lastFix=Date.now();filter=VirtualTrackingCore.createFilter(0,getState().total);phase='walking';setView('walk');setTravel(0);target=0;$('#use-fix').hidden=true;$('#gps-toggle').textContent='Parar caminhada';setStatus($('#tracking-mode').value==='remote'?'P01 guardado aqui. Caminha em linha reta e regressa pelo mesmo caminho.':'Localização pronta. Caminha pelo percurso P01–P03 em Benfica.');$('#gps-accuracy').textContent=`GPS ±${Math.round(accuracy)} m`;}
 function prepUI(now){if(!active||phase!=='preparing')return;const s=preparation.snapshot(now);setStatus(`Fica parado enquanto preparamos o GPS · ${s.count}/5 leituras${s.count&&s.accuracy!==null?` · ±${Math.round(s.accuracy)} m`:''}`);$('#use-fix').hidden=!s.fallback;$('#use-fix').textContent=s.fallback?`Usar leitura atual (±${Math.round(s.fallback.accuracy)} m)`:'Usar leitura atual';if(s.ready)activate(s.position,s.accuracy);}
 function onFix(position,id){if(id!==token||!active)return;const now=Date.now(),c=position.coords,t=position.timestamp;
  if(phase==='preparing'){preparation.add(position,now);prepUI(now);return;}
  if(!Number.isFinite(t)||t<=lastStamp||now-t>10000||t>now+1000||!Number.isFinite(c.latitude)||!Number.isFinite(c.longitude)||Math.abs(c.latitude)>90||Math.abs(c.longitude)>180||!Number.isFinite(c.accuracy)||c.accuracy<0){setStatus('Leitura GPS inválida ou antiga. A aguardar outra.');return;}lastStamp=t;
  if(c.accuracy>20){target=null;setStatus(`GPS ±${Math.round(c.accuracy)} m: posição suspensa até melhorar.`);$('#gps-accuracy').textContent=`GPS ±${Math.round(c.accuracy)} m`;return;}
  const p={lat:c.latitude,lng:c.longitude},state=getState();let along,cross=0;if($('#tracking-mode').value==='remote'){along=TourGeo.distance(origin,p);if(along>state.total+Math.max(20,c.accuracy)){target=null;setStatus('Afastaste-te do trecho de teste. Regressa ao ponto de partida.');return;}}else{const projected=VirtualTrackingCore.mapAlong(p,state.gps,state.cumulative);along=projected.along;cross=projected.cross;if(cross>Math.max(12,c.accuracy)){target=null;setStatus('Estás fora do percurso ou o GPS está desviado. A aguardar.');return;}}
  lastFix=now;lastAccuracy=c.accuracy;$('#gps-accuracy').textContent=`GPS ±${Math.round(c.accuracy)} m`;const filtered=filter.add(Math.min(state.total,Math.max(0,along)),c.accuracy,t,now);if(!filtered.pending&&!filtered.rejected)target=filtered.accepted;
  setStatus(`${filtered.pending?'A confirmar deslocação.':filtered.changed?'Posição atualizada.':'A acompanhar a posição.'} ${c.accuracy>6?'Precisão baixa para este trecho curto.':'Caminha devagar.'}`);
 }
 async function toggleMotion(){if(motion){motionToken++;motion=false;orientation=null;alignment=null;$('#motion-toggle').textContent='Olhar com o telemóvel';$('#motion-toggle').setAttribute('aria-pressed','false');$('#motion-status').textContent='Olhar por toque disponível.';return;}const id=++motionToken;try{if(!window.DeviceOrientationEvent)throw Error('Este navegador não disponibiliza orientação.');const permission=typeof DeviceOrientationEvent.requestPermission==='function'?await DeviceOrientationEvent.requestPermission():'granted';if(id!==motionToken)return;if(permission!=='granted')throw Error('O acesso à orientação não foi permitido.');motion=true;needsAnchor=true;motionAt=Date.now();$('#motion-toggle').textContent='Desligar olhar do telemóvel';$('#motion-toggle').setAttribute('aria-pressed','true');$('#motion-status').textContent='Mantém o telemóvel à tua frente. A aguardar os sensores…';}catch(e){$('#motion-status').textContent=e.message;}}
 function onOrientation(e){if(!motion||![e.alpha,e.beta,e.gamma].every(Number.isFinite))return;const rad=Math.PI/180,angle=(screen.orientation?.angle??window.orientation??0)*rad;const q=new THREE.Quaternion().setFromEuler(new THREE.Euler(e.beta*rad,e.alpha*rad,-e.gamma*rad,'YXZ'));q.multiply(new THREE.Quaternion(-Math.sqrt(.5),0,0,Math.sqrt(.5)));q.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),-angle));if(needsAnchor||!alignment){alignment=lookQuaternion().multiply(q.clone().invert());needsAnchor=false;}orientation=alignment.clone().multiply(q);motionAt=Date.now();$('#motion-status').textContent='Move o telemóvel para olhar à volta.';}
 addEventListener('deviceorientation',onOrientation);addEventListener('orientationchange',()=>needsAnchor=true);
 $('#motion-toggle').onclick=toggleMotion;$('#recenter').onclick=()=>{needsAnchor=true;$('#motion-status').textContent='Olhar recentrado na próxima leitura.';};
 $('#gps-toggle').onclick=()=>{if(active){stop();return;}if(!getState().ready)return;if(!navigator.geolocation){setStatus('Este navegador não disponibiliza GPS.');return;}if(!window.isSecureContext){setStatus('Abre a ligação HTTPS para usar a localização.');return;}const id=++token;active=true;phase='preparing';target=null;lastStamp=-Infinity;preparation=TourGpsStart.createPreparation(Date.now());lock(true);$('#gps-toggle').textContent='Cancelar preparação';$('#gps-toggle').setAttribute('aria-pressed','true');setView('walk');prepUI(Date.now());watch=navigator.geolocation.watchPosition(p=>onFix(p,id),e=>{if(id!==token)return;stop(e.code===1?'Localização não permitida. Autoriza-a nas definições do Safari.':e.code===3?'O GPS demorou demasiado. Tenta novamente ao ar livre.':'Não foi possível obter localização. Tenta ao ar livre.');},{enableHighAccuracy:true,maximumAge:0,timeout:20000});timer=setInterval(()=>{prepUI(Date.now());if(phase==='walking'&&Date.now()-lastFix>10000){target=null;setStatus('Sem localização recente. A deslocação está suspensa.');}},1000);};
 $('#use-fix').onclick=()=>{const s=preparation?.snapshot(Date.now());if(s?.fallback)activate({lat:s.fallback.lat,lng:s.fallback.lng},s.fallback.accuracy);};
 $('#tracking-mode').onchange=()=>{$('#mode-description').textContent=$('#tracking-mode').value==='remote'?'P01 fica onde inicias. Afasta-te em linha reta para avançar e regressa para recuar.':'Usa as coordenadas do percurso real em Benfica. Começa junto ao P01.';};
 document.addEventListener('visibilitychange',()=>{if(document.hidden){if(active)stop('Caminhada parada porque saíste desta página. Reinicia quando regressares.');orientation=null;needsAnchor=true;}});addEventListener('pagehide',()=>{if(active)stop();});
 return {active:()=>active,phase:()=>phase,quaternion:()=>motion&&orientation&&Date.now()-motionAt<3000?orientation:null,target:()=>phase==='walking'&&Date.now()-lastFix<=10000?target:null,stop,motionEnabled:()=>motion};
}
