const assert=require('node:assert/strict');
const C=require('../movement-core.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
const anchor=(e,t=0)=>e.input({type:'anchor',t,along:0,uncertainty:1});
const gps=(e,t,along,extra={})=>e.input({type:'gps',t,along,accuracy:1,stamp:t+100000,age:0,cross:0,...extra});
const tick=(e,from,to)=>{for(let t=from;t<=to;t+=100)e.input({type:'tick',t});return e.snapshot(to);};
test('GPS jitter at rest does not drift',()=>{let e=C.createEstimator({mode:'activity'});anchor(e);e.input({type:'activity',t:0,activity:'stationary'});for(let t=1000;t<60000;t+=1000)gps(e,t,Math.sin(t)*1.2);assert.equal(tick(e,60000,61000).alongMeters,0);});
test('Unknown direction discards steps, never applies backlog',()=>{let e=C.createEstimator({start:0});anchor(e);for(let t=100;t<=1000;t+=100){e.input({type:'activity',t,activity:'walking'});e.input({type:'step',t});}assert.equal(e.snapshot(1000).alongMeters,0);e.input({type:'direction',t:1100,direction:1});e.input({type:'activity',t:1100,activity:'walking'});assert.equal(e.input({type:'step',t:1100}).alongMeters,.65);});
test('Direction expires; orientation cannot reverse travel',()=>{let e=C.createEstimator();anchor(e);e.input({type:'direction',t:0,direction:1});e.input({type:'orientation',t:1,alpha:180});e.input({type:'activity',t:6000,activity:'walking'});assert.equal(e.input({type:'step',t:6000}).alongMeters,0);});
test('Prediction distance/time budgets and explicit reanchor',()=>{let e=C.createEstimator();anchor(e);for(let t=100;t<4000;t+=100){e.input({type:'direction',t,direction:1});e.input({type:'activity',t,activity:'walking'});e.input({type:'step',t});}assert.ok(e.snapshot(4000).alongMeters<=6);assert.equal(e.snapshot(4000).reason,'prediction-budget-exceeded');let e2=C.createEstimator();anchor(e2);e2.input({type:'direction',t:13000,direction:1});e2.input({type:'activity',t:13000,activity:'walking'});assert.equal(e2.input({type:'step',t:13000}).reason,'prediction-budget-exceeded');});
test('Recovery bounded, large discrepancy requires anchor',()=>{let e=C.createEstimator({mode:'activity',total:100});anchor(e);gps(e,1000,5);const s=tick(e,1100,2100);assert.ok(s.alongMeters<1);assert.equal(gps(e,14000,20).reason,'explicit-reanchor-required');assert.ok(e.snapshot(14000).alongMeters<1);});
test('No double count GPS and steps',()=>{let e=C.createEstimator();anchor(e);e.input({type:'direction',t:0,direction:1});e.input({type:'activity',t:100,activity:'walking'});e.input({type:'step',t:100});gps(e,1000,.65);assert.equal(tick(e,1100,2000).alongMeters,.65);});
test('Old duplicate/null fixes and endpoint outlier rejected',()=>{let e=C.createEstimator();anchor(e);gps(e,1000,1);assert.equal(gps(e,1100,2,{stamp:101000}).reason,'gps-invalid-or-old');assert.equal(gps(e,1200,2,{age:10001}).reason,'gps-invalid-or-old');assert.equal(gps(e,1300,2,{accuracy:null}).reason,'gps-invalid-or-old');assert.equal(gps(e,1400,80).reason,'outside-route');assert.equal(e.snapshot(1400).alongMeters,0);});
test('Pause resume cannot integrate hidden time',()=>{let e=C.createEstimator();anchor(e);e.input({type:'pause',t:100});e.input({type:'direction',t:200,direction:1});e.input({type:'activity',t:200,activity:'walking'});assert.equal(e.input({type:'step',t:200}).reason,'explicit-reanchor-required');});
test('Signed remote axis distinguishes lateral movement',()=>{const o={lat:38,lng:-9},p=C.createProjector({origin:o,originAccuracy:1});assert.equal(p.project(o,1),null);assert.equal(p.setAxis({lat:38.00001,lng:-9},1),false);assert.equal(p.setAxis({lat:38.0002,lng:-9},1),true);const side=p.project({lat:38,lng:-8.9999},1);assert.ok(Math.abs(side.along)<.01);assert.ok(side.cross>8);assert.ok(p.project({lat:37.99995,lng:-9},1).along<0);});
test('Arbitrary polyline scales each segment',()=>{const nodes=[{lat:0,lng:0},{lat:.0001,lng:0},{lat:.0002,lng:0},{lat:.0003,lng:0}];const p=C.createProjector({origin:nodes[0],nodes,cumulative:[0,5,10,15]});const r=p.project({lat:.00025,lng:0},1);assert.ok(Math.abs(r.along-12.5)<.01);});
function walk(period=600,rotate=0){const d=C.createDetector();let n=0;for(let t=0;t<10000;t+=20){const z=9.81+2*Math.sin(2*Math.PI*t/period);const s=d.add({t,gravity:{x:0,y:0,z},rotation:{alpha:rotate,beta:0,gamma:0}});if(s.step)n++;}return n;}
test('Slow walking cadence detected; free looking allowed',()=>{assert.ok(walk(1100)>4);assert.ok(walk(600,80)>8);});
test('Fast hand gestures rejected',()=>{assert.equal(walk(100,300),0);assert.equal(walk(600,350),0);});
test('Null fields and sample gaps do not fabricate steps',()=>{const d=C.createDetector();for(let t=0;t<10000;t+=1000)assert.equal(d.add({t,gravity:{x:null,y:null,z:12}}).step,false);assert.equal(d.snapshot(20000).activity,'uncertain');});
test('Replay deterministic and bounded recorder',()=>{const events=[{type:'anchor',t:0},{type:'direction',t:10,direction:1},{type:'activity',t:20,activity:'walking'},{type:'step',t:20}];assert.deepEqual(C.replay(events),C.replay(events));const r=C.createRecorder(2);r.add(events[0]);assert.equal(r.data().events.length,0);r.start();events.forEach(r.add);assert.equal(r.data().events.length,2);assert.equal(r.data().truncated,true);});
console.log(`${count} core tests passed (synthetic; not physical validation).`);
