const C=require('../movement-core.js'),assert=require('node:assert/strict');
function test(name,fn){fn();console.log('PASS '+name);}
test('Reversal first evidence suspends signed prediction',()=>{const e=C.createEstimator();e.input({type:'anchor',t:0,along:5});e.input({type:'direction',t:0,direction:1});e.input({type:'gps',t:1000,stamp:1000,age:0,along:5,accuracy:1,cross:0});const r=e.input({type:'gps',t:2000,stamp:2000,age:0,along:3,accuracy:1,cross:0});assert.equal(r.direction,0);e.input({type:'activity',t:2100,activity:'walking'});assert.equal(e.input({type:'step',t:2100}).alongMeters,5);});
test('Lateral GPS suspends step prediction until a valid fix',()=>{const e=C.createEstimator();e.input({type:'anchor',t:0});e.input({type:'direction',t:0,direction:1});e.input({type:'gps',t:1000,stamp:1000,age:0,along:0,accuracy:1,cross:20});e.input({type:'activity',t:1100,activity:'walking'});assert.equal(e.input({type:'step',t:1100}).reason,'outside-route');assert.equal(e.snapshot(1100).alongMeters,0);});
test('Reanchor resets outage clock, but needs a new direction',()=>{const e=C.createEstimator();e.input({type:'anchor',t:50000});assert.equal(e.snapshot(50000).direction,0);e.input({type:'direction',t:50000,direction:1});e.input({type:'activity',t:50100,activity:'walking'});assert.equal(e.input({type:'step',t:50100}).alongMeters,.65);});
test('Uncertainty budget suspends a poor-origin prediction',()=>{const e=C.createEstimator();e.input({type:'anchor',t:0,uncertainty:12});e.input({type:'direction',t:0,direction:1});e.input({type:'activity',t:100,activity:'walking'});assert.equal(e.input({type:'step',t:100}).alongMeters,0);});
test('GPS age includes acquisition delay',()=>{const e=C.createEstimator({mode:'activity'});e.input({type:'anchor',t:0});e.input({type:'gps',t:9000,stamp:1000,age:8000,along:1,accuracy:1,cross:0});assert.equal(e.snapshot(10000).lastFixAgeMs,9000);assert.equal(e.input({type:'tick',t:12000}).reason,'gps-unavailable');});
test('Movement heading contradicting displacement cannot sign steps',()=>{const e=C.createEstimator();e.input({type:'anchor',t:0});e.input({type:'gps',t:1000,stamp:1000,age:0,along:0,accuracy:1,cross:0});const r=e.input({type:'gps',t:2000,stamp:2000,age:0,along:3,accuracy:1,cross:0,heading:180,tangentHeading:0,speed:1});assert.equal(r.direction,0);assert.equal(r.directionSource,'gps-heading-conflict');});
test('Confirmed direction survives five seconds with recent GPS, expires without it',()=>{const e=C.createEstimator();e.input({type:'anchor',t:0});e.input({type:'direction',t:0,direction:1});e.input({type:'gps',t:6000,stamp:6000,age:0,along:0,accuracy:1,cross:0});e.input({type:'activity',t:6100,activity:'walking'});assert.equal(e.input({type:'step',t:6100}).alongMeters,.65);assert.equal(e.input({type:'tick',t:17000}).direction,0);});
test('GPS noise does not undo steps inside its uncertainty band',()=>{const e=C.createEstimator();e.input({type:'anchor',t:0,uncertainty:6});e.input({type:'direction',t:0,direction:1,source:'start-forward'});e.input({type:'gps',t:100,stamp:100,age:0,along:0,accuracy:6,cross:0});e.input({type:'activity',t:200,activity:'walking'});e.input({type:'step',t:200});e.input({type:'gps',t:1000,stamp:1000,age:0,along:0,accuracy:6,cross:0});assert.equal(e.input({type:'tick',t:1100}).alongMeters,.65)});
test('Small GPS deltas accumulate evidence of direction',()=>{const e=C.createEstimator({mode:'activity'});e.input({type:'anchor',t:0});for(let i=0;i<=4;i++)e.input({type:'gps',t:1000+i*1000,stamp:1000+i*1000,age:0,along:i*.6,accuracy:1,cross:0});assert.equal(e.snapshot(5000).direction,1)});
test('Radial remote start needs only the origin, activity can catch up faster',()=>{const origin={lat:41,lng:-8},p=C.createProjector({origin,originAccuracy:3,radial:true});assert.ok(p.hasAxis());assert.equal(p.project(origin,3).along,0);assert.ok(p.project({lat:41.00001,lng:-8},3).along>1);const e=C.createEstimator({mode:'activity',params:{correctionRate:2}});e.input({type:'anchor',t:0});e.input({type:'gps',t:1000,stamp:1000,age:0,along:3,accuracy:1,cross:0});for(let t=1100;t<=2000;t+=100)e.input({type:'tick',t});assert.ok(e.snapshot(2000).alongMeters>=1.9);assert.ok(e.snapshot(2000).alongMeters<=3)});
